name: CleanArchitecture CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: 📦 Restore Dependencies
        run: dotnet restore CleanArchitecture.sln

      - name: 🏗️ Build Solution
        run: dotnet build CleanArchitecture.sln --no-restore --configuration Release

      - name: 🧪 Run Tests
        run: dotnet test CleanArchitecture.sln --no-build --verbosity normal --configuration Release
